#!/usr/bin/env bash
set -e
set -o pipefail

echo '*********************************************'
echo '** download service account file ...'
echo '*********************************************'

FILENAME="firebase-service-account.json"
BUCKET_NAME=$FIREBASE_BUCKET_NAME

curl -X GET \
  -o "backend/$FILENAME" \
  "https://firebasestorage.googleapis.com/v0/b/$BUCKET_NAME/o/$FILENAME?alt=media&token=$FIREBASE_SERVICE_ACCOUNT_OBJECT_TOKEN"

echo '*********************************************'
echo '** check created file'
echo '*********************************************'
ls -la