#!/usr/bin/env bash
set -e
set -o pipefail

echo '*********************************************'
echo '** download service account file ...'
echo '*********************************************'

FILENAME=$1
BUCKET_NAME=$FIREBASE_BUCKET_NAME

curl -X GET \
  -o "backend/$FILENAME" \
  "https://firebasestorage.googleapis.com/v0/b/$BUCKET_NAME/o/$FILENAME?alt=media&token=4adb6da0-1510-438f-9c7a-e658a2bec874"

echo '*********************************************'
echo '** check created file'
echo '*********************************************'
ls -la